### ISSUE TITLE
Add callback/behaviour for deciding to download/apply an update or not

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub#18]
Currently, when a new firmware is published, nerves_hub will always try to download and apply it. This isn't always a ideal behavior. It's be nice to have defined hooks that can influence the decision to download/apply the firmware. Something like this: (but with a better name)

```elixir
defmodule FirmwareHandler do
   
   @typedoc "Map of meta information about a firmware"
   @type meta() :: map()

   @callback should_download_firmware(meta) :: boolean
   @callback should_apply_firmware(meta) :: boolean
end
```

**Comment by fhunleth** [comment]
Thanks for writing this. I'll eventually need this feature too.
