### ISSUE TITLE
Add support for "products"

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub#63]
Currently the web app lists all devices per tenant. A tenant likely will have multiple products. It is expected that users will want to focus on one product at a time. Some way of filtering or grouping firmware, devices, and deployments on a per product basis would be good.

Some notes on products:
* The `.fw` files contain a `meta-product` tag that has the product name. This could be extracted for to categorize firmware, devices, and deployments.
* The current `fwup` scripts used with Nerves don't force the `meta-product` tag to match what's running on devices. This makes it possible to turn one product into another.
* Companies and individuals change product names. It may be useful to have two or more `meta-product` names that correspond to one "product" in the UI.

**Comment by mobileoverlord** [comment]
@jlmcgehee21 I believe that this handled in master now.

**Comment by jlmcgehee21** [comment]
ah, yeah. I had that PR, and forgot to close. 👍
