### ISSUE TITLE
Pre/Post upgrade hooks

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub#81]
I find that i frequently need to do one time things such as upgrade embedded firmware connected to my devices. I think allowing `nerves_hub` to execute these one off tasks could be beneficial in a lot of cases. It could also allow a "status" of some sort to be updated on the
nerves hub web app if an error happens.

```elixir
defmodule SomeUpgradeHook do
   use NervesHub.PostUpgradeHook

    def upgrade(old_version, new_version) do
      Logger.info "upgrading from #{old_version} to #{new_version}"
      case SomeEmbeddedDevice.upgrade() do
         :ok -> :ok:
         {:error, reason} -> {:error, "Failed to upgrade: #{reason}"}
      end
   end 
end
```

**Comment by fhunleth** [comment]
The intention is that this is executed one time after the reboot that applies the Nerves firmware update?

Why not check the peripheral firmware versions on each boot and upgrade/downgrade if necessary?

**Comment by ConnorRigby** [comment]
> The intention is that this is executed one time after the reboot that applies the Nerves firmware update?

Yeah i thought it would be easy to have a registration of modules or a single module in `uboot_env` along with their results. 

> Why not check the peripheral firmware versions on each boot and upgrade/downgrade if necessary?

Any in my particular project, i use `avrdude` which is beyond unstable. It's basically a diceroll if it works at all. and "checking" the version requires using `Circuits.UART` to open it, which further complicates running `avrdude` for some reason. It's easier to just flash it to a known required version upon an upgrade.

**Comment by ConnorRigby** [comment]
If this is something we don't want to support, i'm fine with implementing it in band of my application. I thought it might be useful to have baked into nerves_hub though.

**Comment by fhunleth** [comment]
You could the version number to the file after a successful avr_dude run.

**Comment by fhunleth** [comment]
I've been burned by multi-part or bundled firmware updates. My problem is debugging what happens when one part gets out-of-sync. There needs to be some infrastructure around making the update all or none, and then it also has to handle a Nerves firmware update that succeeds but then is reverted. It feels complicated. 

If this were redone to always check at boot rather than being a one-time hook, then I'd be more ok. I suspect that the value-add would be less, though.

**Comment by ConnorRigby** [comment]
Yeah i have also been constantly burned by multi-part updates. Maybe i just need to come up with a different or better way of managing my upgrades. Feel free to close if you don't think we should support this feature. (i'm pretty much okay with not supporting it)
